import type { NaiteMessagingTypes } from "naite-types";

export const mockTestResults: NaiteMessagingTypes.TestResult[] = [
  // ========================================
  // Suite 1: MathService - 기본 수학 연산
  // ========================================
  {
    suiteName: "MathService",
    suiteFilePath: "/src/services/math.test.ts",
    testName: "add 함수 - 양수 더하기",
    testFilePath: "/src/services/math.test.ts",
    testLine: 10,
    status: "passed",
    duration: 12,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "add:input",
        value: { a: 10, b: 20 },
        filePath: "/src/services/math.ts",
        lineNumber: 5,
        at: "2024-01-15T10:30:00.001Z",
      },
      {
        key: "add:result",
        value: 30,
        filePath: "/src/services/math.ts",
        lineNumber: 8,
        at: "2024-01-15T10:30:00.002Z",
      },
    ],
  },
  {
    suiteName: "MathService",
    suiteFilePath: "/src/services/math.test.ts",
    testName: "add 함수 - 음수 포함",
    testFilePath: "/src/services/math.test.ts",
    testLine: 18,
    status: "passed",
    duration: 8,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "add:input",
        value: { a: -5, b: 15 },
        filePath: "/src/services/math.ts",
        lineNumber: 5,
        at: "2024-01-15T10:30:01.001Z",
      },
      {
        key: "add:validation",
        value: { isValidA: true, isValidB: true },
        filePath: "/src/services/math.ts",
        lineNumber: 6,
        at: "2024-01-15T10:30:01.002Z",
      },
      {
        key: "add:result",
        value: 10,
        filePath: "/src/services/math.ts",
        lineNumber: 8,
        at: "2024-01-15T10:30:01.003Z",
      },
    ],
  },
  {
    suiteName: "MathService",
    suiteFilePath: "/src/services/math.test.ts",
    testName: "multiply 함수 테스트",
    testFilePath: "/src/services/math.test.ts",
    testLine: 25,
    status: "passed",
    duration: 15,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "multiply:input",
        value: { a: 7, b: 8 },
        filePath: "/src/services/math.ts",
        lineNumber: 15,
        at: "2024-01-15T10:30:02.001Z",
      },
      {
        key: "multiply:result",
        value: 56,
        filePath: "/src/services/math.ts",
        lineNumber: 18,
        at: "2024-01-15T10:30:02.002Z",
      },
    ],
  },
  {
    suiteName: "MathService",
    suiteFilePath: "/src/services/math.test.ts",
    testName: "divide 함수 - 0으로 나누기 예외",
    testFilePath: "/src/services/math.test.ts",
    testLine: 35,
    status: "failed",
    duration: 22,
    receivedAt: new Date().toISOString(),
    error: {
      message: "Division by zero is not allowed",
      stack: "Error: Division by zero\n    at divide (/src/services/math.ts:25:11)",
    },
    traces: [
      {
        key: "divide:input",
        value: { a: 10, b: 0 },
        filePath: "/src/services/math.ts",
        lineNumber: 22,
        at: "2024-01-15T10:30:03.001Z",
      },
      {
        key: "divide:validation",
        value: { divisorIsZero: true },
        filePath: "/src/services/math.ts",
        lineNumber: 23,
        at: "2024-01-15T10:30:03.002Z",
      },
      {
        key: "divide:error",
        value: { type: "DivisionByZeroError", message: "Cannot divide by zero" },
        filePath: "/src/services/math.ts",
        lineNumber: 25,
        at: "2024-01-15T10:30:03.003Z",
      },
    ],
  },

  // ========================================
  // Suite 2: UserService - 사용자 관리
  // ========================================
  {
    suiteName: "UserService",
    suiteFilePath: "/src/services/user.test.ts",
    testName: "getUser - 존재하는 사용자 조회",
    testFilePath: "/src/services/user.test.ts",
    testLine: 12,
    status: "passed",
    duration: 145,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "getUser:request",
        value: { userId: "usr_123abc" },
        filePath: "/src/services/user.ts",
        lineNumber: 10,
        at: "2024-01-15T10:31:00.001Z",
      },
      {
        key: "getUser:dbQuery",
        value: {
          sql: "SELECT * FROM users WHERE id = $1",
          params: ["usr_123abc"],
          executionTime: "32ms",
        },
        filePath: "/src/services/user.ts",
        lineNumber: 15,
        at: "2024-01-15T10:31:00.035Z",
      },
      {
        key: "getUser:cacheCheck",
        value: { cacheHit: false, cacheKey: "user:usr_123abc" },
        filePath: "/src/services/user.ts",
        lineNumber: 18,
        at: "2024-01-15T10:31:00.036Z",
      },
      {
        key: "getUser:result",
        value: {
          id: "usr_123abc",
          name: "김철수",
          email: "chulsoo@example.com",
          createdAt: "2023-06-15T09:00:00Z",
          role: "admin",
        },
        filePath: "/src/services/user.ts",
        lineNumber: 25,
        at: "2024-01-15T10:31:00.140Z",
      },
    ],
  },
  {
    suiteName: "UserService",
    suiteFilePath: "/src/services/user.test.ts",
    testName: "getUser - 존재하지 않는 사용자",
    testFilePath: "/src/services/user.test.ts",
    testLine: 28,
    status: "passed",
    duration: 89,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "getUser:request",
        value: { userId: "usr_nonexistent" },
        filePath: "/src/services/user.ts",
        lineNumber: 10,
        at: "2024-01-15T10:31:01.001Z",
      },
      {
        key: "getUser:dbQuery",
        value: {
          sql: "SELECT * FROM users WHERE id = $1",
          params: ["usr_nonexistent"],
          executionTime: "28ms",
        },
        filePath: "/src/services/user.ts",
        lineNumber: 15,
        at: "2024-01-15T10:31:01.030Z",
      },
      {
        key: "getUser:result",
        value: null,
        filePath: "/src/services/user.ts",
        lineNumber: 25,
        at: "2024-01-15T10:31:01.085Z",
      },
    ],
  },
  {
    suiteName: "UserService",
    suiteFilePath: "/src/services/user.test.ts",
    testName: "createUser - 새 사용자 생성",
    testFilePath: "/src/services/user.test.ts",
    testLine: 42,
    status: "passed",
    duration: 234,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "createUser:input",
        value: {
          name: "박영희",
          email: "younghee@example.com",
          password: "********",
        },
        filePath: "/src/services/user.ts",
        lineNumber: 35,
        at: "2024-01-15T10:31:02.001Z",
      },
      {
        key: "createUser:validation",
        value: {
          emailValid: true,
          passwordStrength: "strong",
          nameLength: 3,
        },
        filePath: "/src/services/user.ts",
        lineNumber: 40,
        at: "2024-01-15T10:31:02.005Z",
      },
      {
        key: "createUser:passwordHash",
        value: { algorithm: "bcrypt", rounds: 12 },
        filePath: "/src/services/user.ts",
        lineNumber: 45,
        at: "2024-01-15T10:31:02.120Z",
      },
      {
        key: "createUser:dbInsert",
        value: {
          sql: "INSERT INTO users (id, name, email, password_hash) VALUES ($1, $2, $3, $4)",
          executionTime: "45ms",
        },
        filePath: "/src/services/user.ts",
        lineNumber: 50,
        at: "2024-01-15T10:31:02.170Z",
      },
      {
        key: "createUser:result",
        value: {
          id: "usr_new456",
          name: "박영희",
          email: "younghee@example.com",
          createdAt: "2024-01-15T10:31:02Z",
        },
        filePath: "/src/services/user.ts",
        lineNumber: 55,
        at: "2024-01-15T10:31:02.230Z",
      },
    ],
  },
  {
    suiteName: "UserService",
    suiteFilePath: "/src/services/user.test.ts",
    testName: "updateUser - 프로필 수정",
    testFilePath: "/src/services/user.test.ts",
    testLine: 65,
    status: "passed",
    duration: 178,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "updateUser:input",
        value: {
          userId: "usr_123abc",
          updates: { name: "김철수 (수정됨)", bio: "개발자입니다." },
        },
        filePath: "/src/services/user.ts",
        lineNumber: 70,
        at: "2024-01-15T10:31:03.001Z",
      },
      {
        key: "updateUser:beforeState",
        value: { name: "김철수", bio: null },
        filePath: "/src/services/user.ts",
        lineNumber: 75,
        at: "2024-01-15T10:31:03.050Z",
      },
      {
        key: "updateUser:dbUpdate",
        value: {
          sql: "UPDATE users SET name = $1, bio = $2 WHERE id = $3",
          rowsAffected: 1,
        },
        filePath: "/src/services/user.ts",
        lineNumber: 80,
        at: "2024-01-15T10:31:03.120Z",
      },
      {
        key: "updateUser:afterState",
        value: { name: "김철수 (수정됨)", bio: "개발자입니다." },
        filePath: "/src/services/user.ts",
        lineNumber: 85,
        at: "2024-01-15T10:31:03.175Z",
      },
    ],
  },

  // ========================================
  // Suite 3: AuthService - 인증 서비스
  // ========================================
  {
    suiteName: "AuthService",
    suiteFilePath: "/src/services/auth.test.ts",
    testName: "login - 정상 로그인",
    testFilePath: "/src/services/auth.test.ts",
    testLine: 8,
    status: "passed",
    duration: 312,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "login:credentials",
        value: { email: "user@example.com", passwordProvided: true },
        filePath: "/src/services/auth.ts",
        lineNumber: 12,
        at: "2024-01-15T10:32:00.001Z",
      },
      {
        key: "login:userLookup",
        value: { found: true, userId: "usr_789xyz" },
        filePath: "/src/services/auth.ts",
        lineNumber: 18,
        at: "2024-01-15T10:32:00.080Z",
      },
      {
        key: "login:passwordVerify",
        value: { valid: true, algorithm: "bcrypt" },
        filePath: "/src/services/auth.ts",
        lineNumber: 25,
        at: "2024-01-15T10:32:00.200Z",
      },
      {
        key: "login:tokenGeneration",
        value: {
          accessToken: "eyJhbGciOiJIUzI1NiIs...",
          refreshToken: "rt_abc123...",
          expiresIn: 3600,
        },
        filePath: "/src/services/auth.ts",
        lineNumber: 35,
        at: "2024-01-15T10:32:00.250Z",
      },
      {
        key: "login:sessionCreate",
        value: { sessionId: "sess_123", deviceInfo: "Chrome/Windows" },
        filePath: "/src/services/auth.ts",
        lineNumber: 42,
        at: "2024-01-15T10:32:00.300Z",
      },
    ],
  },
  {
    suiteName: "AuthService",
    suiteFilePath: "/src/services/auth.test.ts",
    testName: "login - 잘못된 비밀번호",
    testFilePath: "/src/services/auth.test.ts",
    testLine: 35,
    status: "passed",
    duration: 198,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "login:credentials",
        value: { email: "user@example.com", passwordProvided: true },
        filePath: "/src/services/auth.ts",
        lineNumber: 12,
        at: "2024-01-15T10:32:01.001Z",
      },
      {
        key: "login:userLookup",
        value: { found: true, userId: "usr_789xyz" },
        filePath: "/src/services/auth.ts",
        lineNumber: 18,
        at: "2024-01-15T10:32:01.070Z",
      },
      {
        key: "login:passwordVerify",
        value: { valid: false, failedAttempts: 3 },
        filePath: "/src/services/auth.ts",
        lineNumber: 25,
        at: "2024-01-15T10:32:01.180Z",
      },
      {
        key: "login:error",
        value: { code: "INVALID_CREDENTIALS", lockoutWarning: true },
        filePath: "/src/services/auth.ts",
        lineNumber: 28,
        at: "2024-01-15T10:32:01.185Z",
      },
    ],
  },
  {
    suiteName: "AuthService",
    suiteFilePath: "/src/services/auth.test.ts",
    testName: "logout - 세션 종료",
    testFilePath: "/src/services/auth.test.ts",
    testLine: 55,
    status: "passed",
    duration: 67,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "logout:sessionId",
        value: "sess_123",
        filePath: "/src/services/auth.ts",
        lineNumber: 60,
        at: "2024-01-15T10:32:02.001Z",
      },
      {
        key: "logout:tokenRevoke",
        value: { accessTokenRevoked: true, refreshTokenRevoked: true },
        filePath: "/src/services/auth.ts",
        lineNumber: 65,
        at: "2024-01-15T10:32:02.035Z",
      },
      {
        key: "logout:sessionDestroy",
        value: { destroyed: true },
        filePath: "/src/services/auth.ts",
        lineNumber: 70,
        at: "2024-01-15T10:32:02.060Z",
      },
    ],
  },
  {
    suiteName: "AuthService",
    suiteFilePath: "/src/services/auth.test.ts",
    testName: "refreshToken - 토큰 갱신",
    testFilePath: "/src/services/auth.test.ts",
    testLine: 72,
    status: "passed",
    duration: 89,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "refreshToken:input",
        value: { refreshToken: "rt_abc123..." },
        filePath: "/src/services/auth.ts",
        lineNumber: 80,
        at: "2024-01-15T10:32:03.001Z",
      },
      {
        key: "refreshToken:validation",
        value: { valid: true, notExpired: true, notRevoked: true },
        filePath: "/src/services/auth.ts",
        lineNumber: 85,
        at: "2024-01-15T10:32:03.030Z",
      },
      {
        key: "refreshToken:newTokens",
        value: {
          accessToken: "eyJhbGciOiJIUzI1NiIs...(new)",
          expiresIn: 3600,
        },
        filePath: "/src/services/auth.ts",
        lineNumber: 92,
        at: "2024-01-15T10:32:03.080Z",
      },
    ],
  },

  // ========================================
  // Suite 4: OrderService - 주문 처리
  // ========================================
  {
    suiteName: "OrderService",
    suiteFilePath: "/src/services/order.test.ts",
    testName: "createOrder - 새 주문 생성",
    testFilePath: "/src/services/order.test.ts",
    testLine: 15,
    status: "passed",
    duration: 456,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "createOrder:input",
        value: {
          userId: "usr_123abc",
          items: [
            { productId: "prod_001", quantity: 2, price: 15000 },
            { productId: "prod_002", quantity: 1, price: 25000 },
          ],
          shippingAddress: {
            city: "서울",
            district: "강남구",
            detail: "테헤란로 123",
          },
        },
        filePath: "/src/services/order.ts",
        lineNumber: 20,
        at: "2024-01-15T10:33:00.001Z",
      },
      {
        key: "createOrder:inventoryCheck",
        value: {
          prod_001: { available: 50, requested: 2 },
          prod_002: { available: 12, requested: 1 },
          allAvailable: true,
        },
        filePath: "/src/services/order.ts",
        lineNumber: 30,
        at: "2024-01-15T10:33:00.100Z",
      },
      {
        key: "createOrder:priceCalculation",
        value: {
          subtotal: 55000,
          shipping: 3000,
          discount: 5000,
          total: 53000,
        },
        filePath: "/src/services/order.ts",
        lineNumber: 45,
        at: "2024-01-15T10:33:00.150Z",
      },
      {
        key: "createOrder:paymentHold",
        value: { holdId: "hold_xyz789", amount: 53000, status: "held" },
        filePath: "/src/services/order.ts",
        lineNumber: 55,
        at: "2024-01-15T10:33:00.300Z",
      },
      {
        key: "createOrder:dbInsert",
        value: { orderId: "ord_abc123", status: "pending" },
        filePath: "/src/services/order.ts",
        lineNumber: 65,
        at: "2024-01-15T10:33:00.400Z",
      },
      {
        key: "createOrder:result",
        value: {
          orderId: "ord_abc123",
          status: "pending",
          total: 53000,
          estimatedDelivery: "2024-01-18",
        },
        filePath: "/src/services/order.ts",
        lineNumber: 70,
        at: "2024-01-15T10:33:00.450Z",
      },
    ],
  },
  {
    suiteName: "OrderService",
    suiteFilePath: "/src/services/order.test.ts",
    testName: "createOrder - 재고 부족 실패",
    testFilePath: "/src/services/order.test.ts",
    testLine: 55,
    status: "failed",
    duration: 123,
    receivedAt: new Date().toISOString(),
    error: {
      message: "Insufficient inventory for product prod_003",
      stack: "Error: Insufficient inventory\n    at checkInventory (/src/services/order.ts:35:9)",
    },
    traces: [
      {
        key: "createOrder:input",
        value: {
          userId: "usr_456def",
          items: [{ productId: "prod_003", quantity: 100, price: 5000 }],
        },
        filePath: "/src/services/order.ts",
        lineNumber: 20,
        at: "2024-01-15T10:33:01.001Z",
      },
      {
        key: "createOrder:inventoryCheck",
        value: {
          prod_003: { available: 5, requested: 100 },
          allAvailable: false,
          insufficientItems: ["prod_003"],
        },
        filePath: "/src/services/order.ts",
        lineNumber: 30,
        at: "2024-01-15T10:33:01.080Z",
      },
      {
        key: "createOrder:error",
        value: {
          code: "INSUFFICIENT_INVENTORY",
          details: { productId: "prod_003", available: 5, requested: 100 },
        },
        filePath: "/src/services/order.ts",
        lineNumber: 35,
        at: "2024-01-15T10:33:01.090Z",
      },
    ],
  },
  {
    suiteName: "OrderService",
    suiteFilePath: "/src/services/order.test.ts",
    testName: "cancelOrder - 주문 취소",
    testFilePath: "/src/services/order.test.ts",
    testLine: 85,
    status: "passed",
    duration: 234,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "cancelOrder:input",
        value: { orderId: "ord_abc123", reason: "고객 요청" },
        filePath: "/src/services/order.ts",
        lineNumber: 100,
        at: "2024-01-15T10:33:02.001Z",
      },
      {
        key: "cancelOrder:statusCheck",
        value: { currentStatus: "pending", canCancel: true },
        filePath: "/src/services/order.ts",
        lineNumber: 105,
        at: "2024-01-15T10:33:02.050Z",
      },
      {
        key: "cancelOrder:paymentRefund",
        value: { refundId: "ref_123", amount: 53000, status: "refunded" },
        filePath: "/src/services/order.ts",
        lineNumber: 115,
        at: "2024-01-15T10:33:02.150Z",
      },
      {
        key: "cancelOrder:inventoryRestore",
        value: {
          prod_001: { restored: 2 },
          prod_002: { restored: 1 },
        },
        filePath: "/src/services/order.ts",
        lineNumber: 125,
        at: "2024-01-15T10:33:02.200Z",
      },
      {
        key: "cancelOrder:result",
        value: { orderId: "ord_abc123", status: "cancelled" },
        filePath: "/src/services/order.ts",
        lineNumber: 130,
        at: "2024-01-15T10:33:02.230Z",
      },
    ],
  },

  // ========================================
  // Suite 5: NotificationService - 알림 서비스
  // ========================================
  {
    suiteName: "NotificationService",
    suiteFilePath: "/src/services/notification.test.ts",
    testName: "sendEmail - 이메일 발송",
    testFilePath: "/src/services/notification.test.ts",
    testLine: 10,
    status: "passed",
    duration: 567,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "sendEmail:input",
        value: {
          to: "customer@example.com",
          subject: "주문 완료 안내",
          template: "order_confirmation",
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 15,
        at: "2024-01-15T10:34:00.001Z",
      },
      {
        key: "sendEmail:templateRender",
        value: {
          template: "order_confirmation",
          variables: { orderId: "ord_abc123", customerName: "김철수" },
          renderTime: "12ms",
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 25,
        at: "2024-01-15T10:34:00.015Z",
      },
      {
        key: "sendEmail:smtpSend",
        value: {
          messageId: "<abc123@mail.example.com>",
          accepted: ["customer@example.com"],
          rejected: [],
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 40,
        at: "2024-01-15T10:34:00.550Z",
      },
    ],
  },
  {
    suiteName: "NotificationService",
    suiteFilePath: "/src/services/notification.test.ts",
    testName: "sendPush - 푸시 알림 발송",
    testFilePath: "/src/services/notification.test.ts",
    testLine: 35,
    status: "passed",
    duration: 234,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "sendPush:input",
        value: {
          userId: "usr_123abc",
          title: "배송 시작",
          body: "주문하신 상품이 배송 시작되었습니다.",
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 60,
        at: "2024-01-15T10:34:01.001Z",
      },
      {
        key: "sendPush:deviceTokenLookup",
        value: {
          tokens: ["fcm_token_ios_123", "fcm_token_android_456"],
          platforms: ["ios", "android"],
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 65,
        at: "2024-01-15T10:34:01.050Z",
      },
      {
        key: "sendPush:fcmSend",
        value: {
          successCount: 2,
          failureCount: 0,
          results: [
            { messageId: "msg_ios_123", success: true },
            { messageId: "msg_android_456", success: true },
          ],
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 80,
        at: "2024-01-15T10:34:01.220Z",
      },
    ],
  },

  // ========================================
  // Suite 6: CacheService - 캐시 서비스
  // ========================================
  {
    suiteName: "CacheService",
    suiteFilePath: "/src/services/cache.test.ts",
    testName: "get - 캐시 히트",
    testFilePath: "/src/services/cache.test.ts",
    testLine: 8,
    status: "passed",
    duration: 5,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "cache:get",
        value: { key: "user:usr_123abc", hit: true },
        filePath: "/src/services/cache.ts",
        lineNumber: 12,
        at: "2024-01-15T10:35:00.001Z",
      },
      {
        key: "cache:result",
        value: {
          data: { id: "usr_123abc", name: "김철수" },
          ttl: 3600,
          age: 1200,
        },
        filePath: "/src/services/cache.ts",
        lineNumber: 15,
        at: "2024-01-15T10:35:00.003Z",
      },
    ],
  },
  {
    suiteName: "CacheService",
    suiteFilePath: "/src/services/cache.test.ts",
    testName: "get - 캐시 미스",
    testFilePath: "/src/services/cache.test.ts",
    testLine: 22,
    status: "passed",
    duration: 3,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "cache:get",
        value: { key: "user:usr_nonexistent", hit: false },
        filePath: "/src/services/cache.ts",
        lineNumber: 12,
        at: "2024-01-15T10:35:01.001Z",
      },
      {
        key: "cache:result",
        value: null,
        filePath: "/src/services/cache.ts",
        lineNumber: 15,
        at: "2024-01-15T10:35:01.002Z",
      },
    ],
  },
  {
    suiteName: "CacheService",
    suiteFilePath: "/src/services/cache.test.ts",
    testName: "set - 캐시 저장",
    testFilePath: "/src/services/cache.test.ts",
    testLine: 35,
    status: "passed",
    duration: 8,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "cache:set",
        value: {
          key: "product:prod_001",
          ttl: 7200,
          size: "256 bytes",
        },
        filePath: "/src/services/cache.ts",
        lineNumber: 25,
        at: "2024-01-15T10:35:02.001Z",
      },
      {
        key: "cache:setResult",
        value: { success: true, evicted: false },
        filePath: "/src/services/cache.ts",
        lineNumber: 30,
        at: "2024-01-15T10:35:02.006Z",
      },
    ],
  },
  {
    suiteName: "CacheService",
    suiteFilePath: "/src/services/cache.test.ts",
    testName: "invalidate - 캐시 무효화",
    testFilePath: "/src/services/cache.test.ts",
    testLine: 48,
    status: "passed",
    duration: 12,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "cache:invalidate",
        value: { pattern: "user:*", matchedKeys: 15 },
        filePath: "/src/services/cache.ts",
        lineNumber: 40,
        at: "2024-01-15T10:35:03.001Z",
      },
      {
        key: "cache:invalidateResult",
        value: { deletedCount: 15, memoryFreed: "4.2KB" },
        filePath: "/src/services/cache.ts",
        lineNumber: 45,
        at: "2024-01-15T10:35:03.010Z",
      },
    ],
  },

  // ========================================
  // Suite 7: ValidationService - 유효성 검증
  // ========================================
  {
    suiteName: "ValidationService",
    suiteFilePath: "/src/services/validation.test.ts",
    testName: "validateEmail - 유효한 이메일",
    testFilePath: "/src/services/validation.test.ts",
    testLine: 5,
    status: "passed",
    duration: 2,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "validateEmail:input",
        value: "test@example.com",
        filePath: "/src/services/validation.ts",
        lineNumber: 8,
        at: "2024-01-15T10:36:00.001Z",
      },
      {
        key: "validateEmail:result",
        value: { valid: true, normalized: "test@example.com" },
        filePath: "/src/services/validation.ts",
        lineNumber: 15,
        at: "2024-01-15T10:36:00.002Z",
      },
    ],
  },
  {
    suiteName: "ValidationService",
    suiteFilePath: "/src/services/validation.test.ts",
    testName: "validateEmail - 잘못된 형식",
    testFilePath: "/src/services/validation.test.ts",
    testLine: 18,
    status: "passed",
    duration: 1,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "validateEmail:input",
        value: "invalid-email",
        filePath: "/src/services/validation.ts",
        lineNumber: 8,
        at: "2024-01-15T10:36:01.001Z",
      },
      {
        key: "validateEmail:result",
        value: {
          valid: false,
          errors: ["Missing @ symbol", "No domain specified"],
        },
        filePath: "/src/services/validation.ts",
        lineNumber: 15,
        at: "2024-01-15T10:36:01.001Z",
      },
    ],
  },
  {
    suiteName: "ValidationService",
    suiteFilePath: "/src/services/validation.test.ts",
    testName: "validatePassword - 강한 비밀번호",
    testFilePath: "/src/services/validation.test.ts",
    testLine: 32,
    status: "passed",
    duration: 3,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "validatePassword:checks",
        value: {
          length: { min: 8, actual: 12, pass: true },
          uppercase: { required: true, found: 2, pass: true },
          lowercase: { required: true, found: 6, pass: true },
          numbers: { required: true, found: 2, pass: true },
          special: { required: true, found: 2, pass: true },
        },
        filePath: "/src/services/validation.ts",
        lineNumber: 30,
        at: "2024-01-15T10:36:02.001Z",
      },
      {
        key: "validatePassword:result",
        value: { valid: true, strength: "strong", score: 95 },
        filePath: "/src/services/validation.ts",
        lineNumber: 40,
        at: "2024-01-15T10:36:02.002Z",
      },
    ],
  },

  // ========================================
  // Suite 8: ApiController - API 컨트롤러 (복잡한 데이터)
  // ========================================
  {
    suiteName: "ApiController",
    suiteFilePath: "/src/controllers/api.test.ts",
    testName: "GET /api/users - 사용자 목록 조회",
    testFilePath: "/src/controllers/api.test.ts",
    testLine: 12,
    status: "passed",
    duration: 345,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "request:incoming",
        value: {
          method: "GET",
          path: "/api/users",
          query: { page: 1, limit: 10, sort: "createdAt", order: "desc" },
          headers: {
            authorization: "Bearer eyJ...",
            "content-type": "application/json",
            "x-request-id": "req_abc123",
          },
        },
        filePath: "/src/controllers/api.ts",
        lineNumber: 20,
        at: "2024-01-15T10:37:00.001Z",
      },
      {
        key: "auth:verify",
        value: { userId: "usr_admin", role: "admin", permissions: ["read:users", "write:users"] },
        filePath: "/src/middleware/auth.ts",
        lineNumber: 15,
        at: "2024-01-15T10:37:00.050Z",
      },
      {
        key: "db:query",
        value: {
          sql: "SELECT * FROM users ORDER BY created_at DESC LIMIT 10 OFFSET 0",
          executionTime: "45ms",
          rowCount: 10,
        },
        filePath: "/src/repositories/user.ts",
        lineNumber: 30,
        at: "2024-01-15T10:37:00.100Z",
      },
      {
        key: "response:send",
        value: {
          status: 200,
          body: {
            data: [
              { id: "usr_001", name: "사용자1", email: "user1@example.com" },
              { id: "usr_002", name: "사용자2", email: "user2@example.com" },
            ],
            pagination: { page: 1, limit: 10, total: 156, totalPages: 16 },
          },
          headers: { "x-request-id": "req_abc123", "x-response-time": "340ms" },
        },
        filePath: "/src/controllers/api.ts",
        lineNumber: 50,
        at: "2024-01-15T10:37:00.340Z",
      },
    ],
  },
  {
    suiteName: "ApiController",
    suiteFilePath: "/src/controllers/api.test.ts",
    testName: "POST /api/users - 사용자 생성 (대량 데이터)",
    testFilePath: "/src/controllers/api.test.ts",
    testLine: 55,
    status: "passed",
    duration: 678,
    receivedAt: new Date().toISOString(),
    traces: [
      {
        key: "request:body",
        value: {
          users: [
            {
              name: "신규사용자1",
              email: "new1@example.com",
              department: "개발팀",
              metadata: { source: "bulk_import", batchId: "batch_001" },
            },
            {
              name: "신규사용자2",
              email: "new2@example.com",
              department: "마케팅팀",
              metadata: { source: "bulk_import", batchId: "batch_001" },
            },
            {
              name: "신규사용자3",
              email: "new3@example.com",
              department: "영업팀",
              metadata: { source: "bulk_import", batchId: "batch_001" },
            },
          ],
          options: { sendWelcomeEmail: true, assignDefaultRole: true },
        },
        filePath: "/src/controllers/api.ts",
        lineNumber: 80,
        at: "2024-01-15T10:37:01.001Z",
      },
      {
        key: "validation:bulk",
        value: {
          totalItems: 3,
          validItems: 3,
          invalidItems: 0,
          validationTime: "15ms",
        },
        filePath: "/src/services/validation.ts",
        lineNumber: 50,
        at: "2024-01-15T10:37:01.020Z",
      },
      {
        key: "db:bulkInsert",
        value: {
          table: "users",
          insertedCount: 3,
          executionTime: "120ms",
          generatedIds: ["usr_new001", "usr_new002", "usr_new003"],
        },
        filePath: "/src/repositories/user.ts",
        lineNumber: 60,
        at: "2024-01-15T10:37:01.150Z",
      },
      {
        key: "notification:queue",
        value: {
          queueName: "welcome_emails",
          messagesQueued: 3,
          estimatedProcessTime: "~5 minutes",
        },
        filePath: "/src/services/notification.ts",
        lineNumber: 90,
        at: "2024-01-15T10:37:01.200Z",
      },
      {
        key: "audit:log",
        value: {
          action: "BULK_USER_CREATE",
          performedBy: "usr_admin",
          affectedRecords: 3,
          timestamp: "2024-01-15T10:37:01Z",
        },
        filePath: "/src/services/audit.ts",
        lineNumber: 25,
        at: "2024-01-15T10:37:01.250Z",
      },
    ],
  },
];
